### ISSUE TITLE
NEW VERSION Numpy : module 'numpy' has no attribute 'NAN' while using morris.analysis.

### ISSUE THREAD

**Issue by cysey143** [SALib/SALib#631]
Hello,

I was working on a Morris analysis using an API ETABS to do a model updating of a numerical model. It worked just fine til couple days ago. It took me 4 days... to figure it out what was the issue. SaLib seems to have trouve to run Morris analysis with the new Numpy version 2.0.1 released the 21rst of the July.  It works fine with the Numpy 1.26.4.

Here is the error message that I had :

Exception has occurred: AttributeError
module 'numpy' has no attribute 'NAN'
  File "Z:\XXX\Mémoire\MODEL UPDATING\XXXX.py", line 102, in <module>
    Si = analyze(problem, param_values_morris, Y_i[0], num_levels=4)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'numpy' has no attribute 'NAN'

I can send more information if necessary.

I just wanted to adress the issue to help the developers.

Thank you!!

OH I'm sorry I just read the following issue : Migrate to numpy>=2.0.0 #625. sorry for the doublon..

**Comment by tupui** [comment]
Hi 👋 no worries. Will try to make a release soon.
